name: team_3_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_secure_storage: ^9.2.4
  intl:

  # 모델 관리 패키지
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg:

dev_dependencies:
  # 이미지 관리 패키지
  build_runner: ^2.4.6
  flutter_gen_runner:
  flutter_svg:

  # 모델 관리 패키지
  freezed: ^2.4.1
  json_serializable: ^6.7.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# 이미지 관리 설정
flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  # 이미지 위치
  assets:
    - assets/icons/

  # 폰트 설정
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900